<a href="https://colab.research.google.com/github/Maheshtippanu/Algorithms/blob/Floyd-Warshall_algorithm/Floyd_Warshall_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def floyd_warshall(graph):
    # Number of vertices
    num_vertices = len(graph)

    # Initialize distance matrix
    dist = np.full((num_vertices, num_vertices), float('inf'))

    # Set the distance from each vertex to itself to 0
    for i in range(num_vertices):
        dist[i][i] = 0

    # Initialize distances based on the input graph
    for i in range(num_vertices):
        for j in range(num_vertices):
            if graph[i][j] != 0:  # Only set distance if there is an edge
                dist[i][j] = graph[i][j]

    # Update distances using the Floyd-Warshall algorithm
    for k in range(num_vertices):
        for i in range(num_vertices):
            for j in range(num_vertices):
                dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j])

    return dist

# Example usage
if __name__ == "__main__":
    # Example graph represented as a weight matrix
    # 0 indicates no edge between vertices
    graph = [
        [0, 3, float('inf'), 7],
        [8, 0, 2, float('inf')],
        [5, float('inf'), 0, 1],
        [2, float('inf'), float('inf'), 0]
    ]

    shortest_paths = floyd_warshall(graph)

    print("Shortest path matrix:")
    for row in shortest_paths:
        print(row)


Shortest path matrix:
[0. 3. 5. 6.]
[5. 0. 2. 3.]
[3. 6. 0. 1.]
[2. 5. 7. 0.]
